LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional

LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/overlay

LOCAL_RESOURCE_DIR := $(LOCAL_PATH)/res
LOCAL_SDK_VERSION := current
LOCAL_EXPORT_PACKAGE_RESOURCES := true
LOCAL_PROGUARD_ENABLED := disabled
LOCAL_USE_AAPT2 := true
LOCAL_AAPT2_ONLY := true

LOCAL_PACKAGE_NAME := YukawaAndroidOverlay
LOCAL_CERTIFICATE := platform
LOCAL_POST_INSTALL_CMD := \
  cp $(TARGET_OUT_VENDOR)/overlay/$(LOCAL_PACKAGE_NAME)/$(LOCAL_PACKAGE_NAME).apk $(TARGET_OUT_VENDOR)/overlay/$(LOCAL_PACKAGE_NAME).apk; \
  rm -rf $(TARGET_OUT_VENDOR)/overlay/$(LOCAL_PACKAGE_NAME)
include $(BUILD_PACKAGE)
